AllCops:
  Exclude:
    - Rakefile
    - bin/**/*
    - config/environments/**/*
    - config/initializers/**/*
    - config/application.rb
    - config/puma.rb
    - db/schema.rb
    - db/migrate/**/*
    - vendor/**/*
  NewCops: enable

Metrics/AbcSize:
  Max: 36

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 125

Metrics/MethodLength:
  Max: 18

# Not bothering for this repo.
Style/Documentation:
  Enabled: false
