AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Rakefile
    - bin/**/*
    - config/environments/**/*
    - config/initializers/**/*
    - config/application.rb
    - config/puma.rb
    - db/schema.rb
    - db/migrate/**/*
    - vendor/**/*
  NewCops: enable

# Incidents have complicated validation conditions.
Layout/BlockEndNewline:
  Exclude:
    - 'app/models/incident.rb'

Layout/MultilineBlockLayout:
  Exclude:
    - 'app/models/incident.rb'

Layout/MultilineOperationIndentation:
  Exclude:
    - 'app/models/incident.rb'

# It's nice to align the xml tags and their values.
Layout/ExtraSpacing:
  Exclude:
    - 'lib/tasks/incidents.rake'

# It's nice to align the xml tags and their values.
Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'lib/tasks/incidents.rake'

# I've never seen this one go bad.
Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 36

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Max: 125
  Exclude:
    - app/models/incident.rb

Metrics/MethodLength:
  Max: 18

# Not bothering for this repo.
Style/Documentation:
  Enabled: false
