CREATE TABLE incident (
  UID int(11) NOT NULL AUTO_INCREMENT,
  FilePrefix varchar(25) DEFAULT NULL,
  FileNum varchar(25) DEFAULT NULL,
  DateEntered date DEFAULT NULL,
  AppraisalMade enum('yes', 'no', 'request', 'reopen') NOT NULL DEFAULT 'no',
  AppraisalNote text DEFAULT NULL,
  IncidentDate datetime DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  city varchar(255) NOT NULL,
  state varchar(2) NOT NULL,
  zip varchar(20) NOT NULL,
  longitude varchar(20) NOT NULL,
  latitude varchar(20) NOT NULL,
  AccidentCode int(11) NOT NULL DEFAULT 0,
  AccidentCodeGroup int(11) NOT NULL DEFAULT 0,
  Company int(11) DEFAULT NULL,
  IncidentDesc text DEFAULT NULL,
  EmployeeID int(11) DEFAULT NULL,
  Driver int(11) DEFAULT NULL,
  DriverDesc text DEFAULT NULL,
  VehicleRouteNum varchar(100) DEFAULT NULL,
  VehicleDestination varchar(100) DEFAULT NULL,
  VehicleNum varchar(50) DEFAULT NULL,
  VehicleAppraisalAmnt decimal(19, 0) DEFAULT NULL,
  VehicleDamageArea varchar(100) DEFAULT NULL,
  Comments text DEFAULT NULL,
  ReportGiver varchar(50) DEFAULT NULL,
  PointOfContact varchar(100) DEFAULT NULL,
  TotalSettlement double(10, 2) DEFAULT 0.00,
  Status enum('ir', 'new', 'open', 'closed', 'reopened', 'down', 'duplicate') NOT NULL,
  CloseDate date DEFAULT NULL,
  ReopenDate date DEFAULT NULL,
  DownDate date DEFAULT NULL,
  ac_type varchar(10) DEFAULT NULL,
  reason1 varchar(100) NOT NULL,
  reason2 varchar(100) NOT NULL,
  PRIMARY KEY (UID)
);

CREATE TABLE drivers_report (
  UID int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (UID)
);
