CREATE TABLE incident (
  UID int(11) NOT NULL AUTO_INCREMENT,
  FilePrefix varchar(25) DEFAULT NULL,
  FileNum varchar(25) DEFAULT NULL,
  DateEntered date DEFAULT NULL,
  AppraisalMade enum('yes', 'no', 'request', 'reopen') NOT NULL DEFAULT 'no',
  AppraisalNote text DEFAULT NULL,
  IncidentDate datetime DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  city varchar(255) NOT NULL,
  state varchar(2) NOT NULL,
  zip varchar(20) NOT NULL,
  longitude varchar(20) NOT NULL,
  latitude varchar(20) NOT NULL,
  AccidentCode int(11) NOT NULL DEFAULT 0,
  AccidentCodeGroup int(11) NOT NULL DEFAULT 0,
  Company int(11) DEFAULT NULL,
  IncidentDesc text DEFAULT NULL,
  EmployeeID int(11) DEFAULT NULL,
  Driver int(11) DEFAULT NULL,
  DriverDesc text DEFAULT NULL,
  VehicleRouteNum varchar(100) DEFAULT NULL,
  VehicleDestination varchar(100) DEFAULT NULL,
  VehicleNum varchar(50) DEFAULT NULL,
  VehicleAppraisalAmnt decimal(19, 0) DEFAULT NULL,
  VehicleDamageArea varchar(100) DEFAULT NULL,
  Comments text DEFAULT NULL,
  ReportGiver varchar(50) DEFAULT NULL,
  PointOfContact varchar(100) DEFAULT NULL,
  TotalSettlement double(10, 2) DEFAULT 0.00,
  Status enum('ir', 'new', 'open', 'closed', 'reopened', 'down', 'duplicate') NOT NULL,
  CloseDate date DEFAULT NULL,
  ReopenDate date DEFAULT NULL,
  DownDate date DEFAULT NULL,
  ac_type varchar(10) DEFAULT NULL,
  reason1 varchar(100) NOT NULL,
  reason2 varchar(100) NOT NULL,
  PRIMARY KEY (UID)
);

CREATE TABLE drivers_report (
  UID int(11) NOT NULL AUTO_INCREMENT,
  FileID int(11) DEFAULT NULL,
  PolicePresent enum('yes', 'no') NOT NULL DEFAULT 'no',
  OfficerName varchar(100) DEFAULT NULL,
  BadgeNum varchar(50) DEFAULT NULL,
  ArrivalTime varchar(50) DEFAULT NULL,
  Citation varchar(3) DEFAULT NULL,
  CitationWho varchar(255) DEFAULT NULL,
  Weather varchar(255) DEFAULT NULL,
  SurrCond varchar(255) DEFAULT NULL,
  Lighting varchar(50) DEFAULT NULL,
  LossLocation varchar(255) DEFAULT NULL,
  Speed varchar(50) DEFAULT NULL,
  MotionBus varchar(50) DEFAULT NULL,
  Direction varchar(6) DEFAULT NULL,
  ChairOnLift enum('yes', 'no') NOT NULL DEFAULT 'no',
  LiftDeployed enum('yes', 'no') NOT NULL DEFAULT 'no',
  PassengersPresent varchar(3) DEFAULT NULL,
  SeatBelts varchar(3) DEFAULT NULL,
  PointOfContact varchar(100) DEFAULT NULL,
  CurbDist varchar(100) DEFAULT NULL,
  VehicleDistance varchar(100) DEFAULT NULL,
  ReviewFlg tinyint(1) DEFAULT 0,
  TotalPass varchar(100) DEFAULT NULL,
  PVTAatFault enum('no', 'yes') DEFAULT 'no',
  Wheelchair enum('yes', 'no') DEFAULT 'no',
  YellowLine enum('yes', 'no') DEFAULT 'no',
  NotReported enum('no', 'yes') DEFAULT 'no',
  Ambulance enum('no', 'yes') DEFAULT 'no',
  OVTow enum('no', 'yes') DEFAULT 'no',
  PVTATow enum('no', 'yes') DEFAULT 'no',
  Fatality enum('no', 'yes') DEFAULT 'no',
  assistRequest enum('na', 'no', 'yes') DEFAULT 'na',
  PD enum('no', 'yes') DEFAULT 'no',
  Note text DEFAULT NULL,
  externalAppraisal decimal(10, 2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (UID)
);
