name: ci
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
        ports:
          - 3306:3306
    env:
      RAILS_ENV: test
      DATABASE_URL: trilogy://root@127.0.0.1:3306/incidents_test
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bin/setup
      - run: bundle exec rspec
      - name: Archive failed system test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: tmp/capybara/*.png
          if-no-files-found: ignore
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - run: bundle exec brakeman --no-pager
